class Matrix:
    def __init__(self, rows:int, cols:int, rand:bool = False, low:float = 0.0, high:float = 1.0, seed:int = 0) -> None:...
    def __add__(self, other:'Matrix') -> 'Matrix': ...
    def get(self, row: int, col: int) -> float:...